/* Reliability and accessibility around the existing SwiftShop flows. */
(() => {
  'use strict';
  const email='dancu1213t@gmail.com';
  const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e;};
  const button=(text,run)=>{const b=node('button',text);b.type='button';b.onclick=run;return b;};
  const money=n=>'$'+Number(n||0).toFixed(2)+' BZD';
  let catalogueState='loading';
  window.addEventListener('swift-catalogue-state',e=>{catalogueState=e.detail.state;window.SwiftQuality?.catalogue(catalogueState);});
  function start(){
    const app=document.getElementById('appScreen');if(!app)return;
    const dialog=node('dialog',null,'sq-dialog');dialog.id='swiftQualityDialog';dialog.setAttribute('aria-labelledby','sqTitle');
    const heading=node('h2');heading.id='sqTitle';const close=button('Close',()=>dialog.close());close.setAttribute('aria-label','Close this page');
    const head=node('header');head.append(heading,close);const content=node('div',null,'sq-content');dialog.append(head,content);document.body.append(dialog);
    let onDismiss=null;
    content.addEventListener('click',event=>{const a=event.target.closest('a[href]');if(a?.getAttribute('href')==='delete-account.html'){event.preventDefault();deletion();}else if(a?.getAttribute('href')==='privacy.html'){event.preventDefault();policy('privacy.html','Privacy policy');}});
    dialog.addEventListener('close',()=>{onDismiss?.();onDismiss=null;});
    function show(title){if(dialog.open)dialog.close();heading.textContent=title;content.replaceChildren();dialog.inert=false;dialog.showModal();content.scrollTop=0;}
    function emailLink(subject,body){const a=node('a','Open email draft','sq-action');a.href='mailto:'+email+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);return a;}
    async function policy(file,title){show(title);const loading=node('p','Loading…');content.append(loading);try{const response=await fetch(file,{signal:AbortSignal.timeout(5000)});if(!response.ok)throw Error();const parsed=new DOMParser().parseFromString(await response.text(),'text/html');if(!dialog.open||heading.textContent!==title)return;content.replaceChildren(...[...parsed.querySelector('main').children].map(e=>document.importNode(e,true)));}catch{loading.textContent='This page could not load.';content.append(button('Retry',()=>policy(file,title)));}}
    function support(){show('Help & support');content.append(node('p','For help with an order, ride, payment, or your account, contact SwiftShop.'),node('p',email,'sq-email'),emailLink('SwiftShop support','Hello SwiftShop,\n\nI need help with:\n\nOrder or ride reference (if available):\n\n'));content.append(node('p','Your email app opens a draft for you to review and send. Do not include passwords, payment-card details, or private keys.','sq-note'));}
    function deletion(){show('Delete account & data');content.append(node('p','Request deletion of your SwiftShop account and associated personal data. Support will verify ownership before processing the request.'),node('p','This includes your customer profile and associated delivery, ride, and notification data, except records that must be retained for legal, financial, safety, or fraud-prevention reasons. Support will explain any retained records.'),node('p','This is a request, not an immediate deletion. Opening the email draft does not send it or cancel an active order or ride.'));
      const direct=button('Submit verified deletion request',async()=>{direct.disabled=true;try{const {data,error}=await customerDataClient.rpc('swift_request_account_deletion').abortSignal(AbortSignal.timeout(10000));if(error)throw error;direct.textContent='Request received';content.append(node('p','Request '+data.id+' is '+data.status+'. Support will review and process your account and associated data.'));}catch(e){content.append(node('p',e.message+'. You can also use the email request below.'));direct.disabled=false;}});content.append(direct);
      const label=node('label','Account phone number');label.htmlFor='sqDeletePhone';const input=node('input');input.id='sqDeletePhone';input.type='tel';input.autocomplete='tel';input.value=localStorage.getItem('userPhone')||'';label.append(input);content.append(label);
      const a=emailLink('SwiftShop account and data deletion request','');const update=()=>{a.href='mailto:'+email+'?subject='+encodeURIComponent('SwiftShop account and data deletion request')+'&body='+encodeURIComponent('Hello SwiftShop,\n\nPlease delete my account and associated personal data.\nAccount phone number: '+input.value.trim()+'\n\nPlease contact me to verify account ownership and explain any records that must be retained.');};input.addEventListener('input',update);update();content.append(a,node('p','No email app? Send the same request to '+email+'. Include the account phone number so support can locate your account.','sq-note'),button('View privacy policy',()=>policy('privacy.html','Privacy policy')));
    }
    const preferences=document.querySelector('#profileOverlay .profile-preferences');
    if(preferences){const section=node('section',null,'sq-account');section.setAttribute('aria-label','Support and privacy');section.append(node('h3','Support & privacy'),button('Notification settings',()=>window.SwiftDeliveryNotifications?.open()),button('Help & support',support),button('Privacy policy',()=>policy('privacy.html','Privacy policy')),button('Delete account & data',deletion));preferences.after(section);}
    const login=document.getElementById('authScreen');if(login){const privacy=button('Privacy policy',()=>policy('privacy.html','Privacy policy'));privacy.className='sq-login-privacy';login.append(privacy);}
    const live=node('p',null,'sq-sr-only');live.setAttribute('role','status');live.setAttribute('aria-live','polite');app.append(live);
    const connection=node('div',null,'sq-connection');connection.setAttribute('role','status');connection.hidden=true;app.querySelector('.header')?.after(connection);
    function connected(){connection.hidden=navigator.onLine!==false;connection.textContent='You’re offline. Browse what’s loaded; reconnect to place orders or refresh live updates.';if(navigator.onLine)window.SwiftDeliveryNotifications?.sync();}
    window.addEventListener('online',connected);window.addEventListener('offline',connected);connected();
    const catalogue=node('section',null,'sq-catalogue');catalogue.setAttribute('aria-live','polite');const status=node('p');const retry=button('Retry loading',async()=>{if(retry.disabled)return;retry.disabled=true;try{const products=await getProducts();if(catalogueState!=='error'){allProducts=products;render();}}finally{retry.disabled=false;}});catalogue.append(status,retry);document.getElementById('products')?.before(catalogue);
    function paintCatalogue(state){catalogue.hidden=state==='ready';retry.hidden=state!=='error';status.textContent=state==='loading'?'Loading local favourites…':state==='error'?'We couldn’t load the catalogue. Check your connection and try again.':'No products are available yet. Check back soon.';catalogue.setAttribute('aria-busy',String(state==='loading'));}
    window.SwiftQuality={catalogue:paintCatalogue};paintCatalogue(window.swiftCatalogueState||catalogueState);
    // Local cart drafts are account-scoped; successful submission persists the empty cart.
    const draftKey=()=> 'swiftshop.cart-draft.v1:'+encodeURIComponent(localStorage.getItem('userPhone')||'guest');
    let draftScope=draftKey();
    function saveCart(){if(draftScope!==draftKey())return;try{localStorage.setItem(draftScope,JSON.stringify({items:cart,savedAt:Date.now()}));}catch{live.textContent='Your cart could not be saved on this device.';}}
    function restoreCart(){try{const saved=JSON.parse(localStorage.getItem(draftKey())||'null');if(!saved?.items||Date.now()-saved.savedAt>86400000)return;const restored={};for(const [name,item] of Object.entries(saved.items)){if(name.length<=200&&Number.isInteger(item.q)&&item.q>0&&item.q<=999&&Number.isFinite(item.p)&&item.p>=0&&typeof item.cat==='string')Object.defineProperty(restored,name,{value:item,writable:true,enumerable:true,configurable:true});}cart=restored;total=Object.values(cart).reduce((sum,item)=>sum+item.q*item.p,0);}catch{}}
    if(!Object.keys(cart).length)restoreCart();
    const bubble=window.updateCartBubble;
    window.updateCartBubble=function(...args){if(draftScope!==draftKey()){draftScope=draftKey();cart={};restoreCart();}saveCart();const result=bubble?.apply(this,args);return result;};
    window.updateCartBubble();
    window.addEventListener('pagehide',saveCart);window.addEventListener('swift-order-submitted',()=>{saveCart();live.textContent='Order sent to SwiftShop. Your cart is now clear.';});
    const logout=window.handleLogout;if(logout)window.handleLogout=async function(...args){if(!confirm('Log out of SwiftShop?'))return;saveCart();window.swiftLogoutConfirmed=true;try{const result=await logout.apply(this,args);if(!localStorage.getItem('userPhone')){cart={};total=0;}return result;}finally{window.swiftLogoutConfirmed=false;}};
    const checkout=document.getElementById('orderBox'),submit=checkout?.querySelector('.submit-inner');
    if(submit){const summary=node('section',null,'sq-review');summary.setAttribute('aria-label','Final order review');const title=node('h3','Order review');const lines=node('div');summary.append(title,lines);(submit.closest('.submit-track')||submit).before(summary);
      function review(){const subtotal=Object.values(cart).reduce((sum,item)=>sum+item.q*item.p,0),delivery=getCartDeliveryFee(),tip=Math.max(0,Number(document.getElementById('selectedTipAmount')?.value)||0);lines.replaceChildren();for(const [label,value] of [['Items',subtotal],['Delivery',delivery],['Platform fee',PLATFORM_FEE],['Optional tip',tip],['Total',subtotal+delivery+PLATFORM_FEE+tip]]){const row=node('div',null,'sq-review-row');row.append(node('span',label),node('strong',money(value)));lines.append(row);}if(localStorage.getItem('tacoOrder'))lines.append(node('p','The separate taco request cost is additional and will be confirmed by Dispatch.','sq-note'));lines.append(node('p','Payment: '+(document.getElementById('paymentMethod')?.value||'Choose a payment method'),'sq-note'));}
      new MutationObserver(()=>{if(checkout.style.display!=='none')review();}).observe(checkout,{attributes:true,attributeFilter:['style']});checkout.addEventListener('change',review);checkout.addEventListener('input',review);checkout.addEventListener('click',event=>{if(event.target.closest('.tip-btn'))review();});review();}
    function labels(root){for(const label of root.querySelectorAll('label')){const input=label.nextElementSibling;if(!label.htmlFor&&input?.matches('input,select,textarea')&&input.id)label.htmlFor=input.id;}for(const b of root.querySelectorAll('.minus-btn')){const name=b.closest('div')?.parentElement?.querySelector('strong')?.textContent;b.setAttribute('aria-label',name?'Remove one '+name:'Remove one item');}for(const input of root.querySelectorAll('input,textarea,select'))if(!input.getAttribute('aria-label')&&!input.labels?.length&&input.placeholder)input.setAttribute('aria-label',input.placeholder);}
    for(const [id,title] of [['profileOverlay','Your profile'],['cartPanel','Your cart']]){const pane=document.getElementById(id);if(pane){pane.setAttribute('role','dialog');pane.setAttribute('aria-label',title);}}
    document.getElementById('customerLiveOrder')?.setAttribute('aria-labelledby','cloTitle');
    for(const [id,label] of [['paymentMethod','Payment method'],['deliveryZoneSelect','Delivery area'],['scheduleTime','Scheduled delivery time']])document.getElementById(id)?.setAttribute('aria-label',label);
    labels(document);const cartItems=document.getElementById('cartPanelItems');if(cartItems)new MutationObserver(()=>{labels(cartItems);if(!Object.keys(cart).length){const empty=node('div',null,'sq-empty-cart');empty.append(node('h3','Your cart is empty'),node('p','Find something you love from a local store.'),button('Browse stores',()=>window.closeCart()));if(!cartItems.querySelector('.sq-empty-cart'))cartItems.append(empty);}}).observe(cartItems,{childList:true});
    // Explain location use before the first OS prompt. Denial leaves manual entry available.
    const geo=navigator.geolocation;if(geo){const original=geo.getCurrentPosition.bind(geo);let awaitingLocation;
      async function permission(){if(localStorage.getItem('swiftshop.location-disclosure')==='seen')return true;if(awaitingLocation)return awaitingLocation;awaitingLocation=new Promise(resolve=>{show('Use your location?');content.append(node('p','SwiftShop uses your location while you use the app to pin delivery addresses, choose ride pickups, and calculate routes. Your selected pickup, destination, or delivery location is shared with Dispatch and the assigned runner or driver to fulfil your request. Google Maps provides maps and routing.'),node('p','You can choose a location manually instead.'));const finish=value=>{if(value)localStorage.setItem('swiftshop.location-disclosure','seen');onDismiss=null;dialog.close();resolve(value);};content.append(button('Continue',()=>finish(true)),button('Choose manually',()=>finish(false)));onDismiss=()=>resolve(false);}).finally(()=>{awaitingLocation=null;});return awaitingLocation;}
      try{geo.getCurrentPosition=(success,failure,options)=>{permission().then(ok=>{if(ok)original(success,failure,options);else failure?.({code:1,message:'Choose a location manually or allow location access.'});});};}catch{}
    }
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
