/* Verified email customers; existing balances require an independently approved claim. */
(()=>{
 document.addEventListener('DOMContentLoaded',()=>{
 const login=document.getElementById('loginBox');if(!login)return;
 const make=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
 const styles=make('style');styles.textContent='#loginBox #customerAuthModes{display:flex;gap:4px;padding:5px;margin:22px 0 10px;background:#f2f2ec;border:1px solid #e7e8df;border-radius:18px}#loginBox #customerAuthModes button{flex:1;width:auto;margin:0;padding:12px 8px;border:0;border-radius:13px;font:inherit;font-size:14px;font-weight:700;background:transparent!important;color:#6d756c!important;box-shadow:none!important}#loginBox #customerAuthModes button[aria-pressed="true"]{background:#fff!important;color:#252f27!important;box-shadow:0 2px 7px #24332512!important}#loginBox #customerAuthModes button:focus-visible{outline:2px solid #ff7200;outline-offset:2px}#loginBox #customerAuthModeHelp{font-size:13px;line-height:1.5;color:#6d756c;margin:0 0 18px}#loginBox #customerAuthRemember{font-size:12px;line-height:1.5;color:#7c8378;margin:14px 0 0}';document.body.append(styles);
 const modes=make('div');modes.id='customerAuthModes';modes.setAttribute('role','group');modes.setAttribute('aria-label','Sign in or sign up');
 const signIn=make('button','Sign in'),signUp=make('button','Sign up');signIn.id='customerSignIn';signUp.id='customerSignUp';signIn.type=signUp.type='button';modes.append(signIn,signUp);
 const help=make('p');help.id='customerAuthModeHelp';
 const remember=make('p','Stay signed in on this device until you log out.');remember.id='customerAuthRemember';
 const email=make('input');email.type='email';email.id='customerAuthEmail';email.placeholder='Email address';email.autocomplete='email';email.setAttribute('aria-label','Email address');
 const code=make('input');code.id='customerAuthCode';code.placeholder='Email verification code';code.autocomplete='one-time-code';code.inputMode='numeric';code.hidden=true;code.setAttribute('aria-label','Email verification code');
 const password=make('input');password.id='customerAuthPassword';password.type='password';password.placeholder='Your password';password.autocomplete='current-password';password.setAttribute('aria-label','Password');
 const passwordLabel=make('label','Password');passwordLabel.setAttribute('for',password.id);passwordLabel.className='customer-auth-label';
 const confirm=make('input');confirm.id='customerAuthPasswordConfirm';confirm.type='password';confirm.autocomplete='new-password';confirm.placeholder='Repeat your password';confirm.setAttribute('aria-label','Confirm password');
 const confirmLabel=make('label','Confirm password');confirmLabel.setAttribute('for',confirm.id);confirmLabel.className='customer-auth-label';
 const emailLabel=make('label','Email address');emailLabel.setAttribute('for',email.id);emailLabel.setAttribute('class','customer-auth-label');const codeLabel=make('label','Verification code');codeLabel.setAttribute('for',code.id);codeLabel.setAttribute('class','customer-auth-label');codeLabel.hidden=true;
 const status=make('p');status.id='customerAuthStatus';status.setAttribute('role','status');status.setAttribute('aria-live','polite');
 const send=login.querySelector('button[onclick="handleLogin()"]');send.before(modes,help,emailLabel,email,passwordLabel,password,confirmLabel,confirm,codeLabel,code);send.after(status,remember);
 const recover=make('button','Forgot password or need to set one?');recover.type='button';recover.id='customerAuthRecover';send.after(recover);
 const contacts=document.getElementById('customerContactSetup');contacts.hidden=true;
 const hero=make('section');hero.id='customerAuthHero';hero.setAttribute('aria-label','Welcome to SwiftShop');
 const brand=make('p','SWIFTSHOP'),headline=make('h1','Your local favourites. One SwiftShop.'),intro=make('p','Shop nearby, get it delivered, or find your next ride. All in one place.');
 brand.className='auth-brand';intro.className='auth-intro';hero.append(brand,headline,intro);login.before(hero);
 const layout=make('style');layout.textContent=`
 #authScreen.auth-screen{min-height:100svh!important;width:100%!important;max-width:none!important;margin:0!important;padding:36px 24px!important;box-sizing:border-box;align-items:center!important;justify-content:center!important;background:#fffaf5!important;gap:0}
 #customerAuthHero{display:none}#authScreen #loginBox{display:block!important;box-sizing:border-box;width:100%!important;max-width:480px!important;margin:0!important;padding:32px!important;text-align:left!important;border-radius:28px!important;background:#fff!important;box-shadow:0 20px 70px #3e27100a!important}
 #authScreen #loginBox h2{font-size:clamp(26px,2.4vw,38px)!important;line-height:1.15!important;letter-spacing:-1px;margin:18px 0 12px!important}#authScreen #loginBox .login-slogan{text-align:left!important;font-size:14px!important;line-height:1.6}
 #authScreen #loginBox input{display:block;width:100%!important;max-width:none!important;box-sizing:border-box;height:54px!important;margin:6px 0 16px!important;padding:0 16px!important;border-radius:14px!important}#authScreen #loginBox label{display:block;text-align:left;font-size:13px;font-weight:600;margin-top:12px}
 #authScreen #loginBox input[hidden],#authScreen #loginBox label[hidden],#authScreen #loginBox button[hidden],#authScreen #loginBox fieldset[hidden]{display:none!important}
 #authScreen #loginBox button{width:100%!important;max-width:none!important;min-height:50px;margin:10px 0 0!important;border-radius:14px!important}#authScreen #loginBox #customerAuthRecover,#authScreen #loginBox #customerAuthChange{background:transparent!important;color:#6b5140!important;box-shadow:none!important;font-size:13px;min-height:36px;padding:8px!important}
 #authScreen #loginBox #customerAuthModes button{background:transparent!important;color:#766b61!important;margin:0!important;min-height:44px!important;padding:10px!important}#authScreen #loginBox #customerAuthModes button[aria-pressed="true"]{background:#fff!important;color:#29211b!important;box-shadow:0 2px 8px #30201012!important}
 #customerAuthStatus{font-size:13px;line-height:1.6;color:#694126;overflow-wrap:anywhere}#authScreen #loginBox .login-steps{font-size:11px!important;margin-top:24px!important;text-align:center}#customerContactSetup{border:0;padding:0;margin:20px 0}
 @media(min-width:900px){#authScreen.auth-screen{display:grid!important;grid-template-columns:minmax(0,1.1fr) minmax(0,1fr);padding:0!important;align-items:stretch!important}#customerAuthHero{display:flex;flex-direction:column;justify-content:center;position:relative;overflow:hidden;padding:clamp(48px,7vw,120px);background:linear-gradient(145deg,#ff6a00,#ff9b40);color:#211f1b;text-align:left;min-height:100svh;box-sizing:border-box}#customerAuthHero::after{content:'';position:absolute;width:580px;height:580px;bottom:-390px;right:-160px;border:70px solid #ffffff28;border-radius:50%;pointer-events:none}#customerAuthHero .auth-brand{font-size:16px;font-weight:800;letter-spacing:4px;margin:0 0 64px}#customerAuthHero h1{font-size:clamp(48px,5vw,84px);line-height:1.04;letter-spacing:-3px;max-width:650px;margin:0 0 28px;color:#211f1b}#customerAuthHero .auth-intro{font-size:clamp(17px,1.4vw,22px);line-height:1.6;max-width:470px;margin:0}#authScreen #loginBox{align-self:center;justify-self:center;max-width:640px!important;width:100%!important;padding:clamp(36px,5vw,80px)!important;background:transparent!important;box-shadow:none!important;border-radius:0!important}}
 @media(max-width:480px){#authScreen.auth-screen{padding:24px 16px!important}#authScreen #loginBox{padding:24px!important}}
 `;layout.textContent=layout.textContent.replaceAll('#authScreen','html.swift-design #authScreen');document.body.append(layout);
 let pendingEmail='',pendingName='',pendingPhone='',busy=false,mode='signin',passwordSaved=false;
 function renderMode(){signIn.setAttribute('aria-pressed',String(mode==='signin'));signUp.setAttribute('aria-pressed',String(mode==='signup'));signIn.disabled=signUp.disabled=busy||!!pendingEmail;help.textContent=mode==='signin'?'Welcome back. Sign in with your email and password.':mode==='signup'?'Create an account. We’ll verify your email before you continue.':'Verify your email to securely set a new password.';password.autocomplete=mode==='signin'?'current-password':'new-password';confirm.hidden=confirmLabel.hidden=mode==='signin';recover.hidden=mode!=='signin';if(!pendingEmail)send.textContent=mode==='signin'?'Sign in':mode==='signup'?'Create account':'Send verification code';}
 recover.onclick=()=>{if(busy||pendingEmail)return;mode='recover';password.value=confirm.value='';status.textContent='';renderMode();};
 function validatePassword(){if(!password.value)throw Error('Enter your password.');if(mode!=='signin'){if(password.value.length<8)throw Error('Use a password with at least 8 characters.');if(password.value!==confirm.value)throw Error('Passwords do not match.');}}
 async function savePassword(){if(pendingEmail&&!passwordSaved&&mode!=='signin'){validatePassword();const {error}=await customerDataClient.auth.updateUser({password:password.value});if(error)throw error;passwordSaved=true;password.value=confirm.value='';password.hidden=passwordLabel.hidden=confirm.hidden=confirmLabel.hidden=true;}}
 function chooseMode(next){if(busy||pendingEmail)return;mode=next;status.textContent='';renderMode();}
 signIn.onclick=()=>chooseMode('signin');signUp.onclick=()=>chooseMode('signup');renderMode();
 function resetContact(){contacts.hidden=true;pendingName='';pendingPhone='';document.getElementById('userName').value='';document.getElementById('userPhone').value='';}
 function authScreen(){document.getElementById('appScreen').style.display='none';document.getElementById('authScreen').style.display='flex';}
 async function finish(animate=false){const result=await customerDataClient.rpc('swift_customer_profile',{p_name:pendingName||null,p_phone:pendingPhone||null}).abortSignal(AbortSignal.timeout(10000));if(result.error)throw result.error;const p=result.data;if(!p){contacts.hidden=false;code.hidden=true;codeLabel.hidden=true;change.hidden=false;send.textContent='Save delivery contact';status.textContent='Email verified. Add your name and phone so stores and drivers can reach you.';document.getElementById('userName').focus();return false;}if(p.claim_required){status.textContent=p.message+' Email dancu1213t@gmail.com, then return here after approval.';send.textContent='Check account approval';return false;}
 localStorage.setItem('userName',p.name||'Customer');localStorage.setItem('userPhone',p.phone);localStorage.setItem('points',p.points||0);localStorage.setItem('loggedIn','true');customerName=p.name;customerPhone=p.phone;customerEmail=p.email;window.userPhone=p.phone;code.value='';code.hidden=true;codeLabel.hidden=true;document.documentElement?.classList.remove('swift-awaiting-auth');if(animate&&window.showSwiftShopWelcome)window.showSwiftShopWelcome(enterApp);else enterApp();return true;}
 window.handleLogin=async()=>{if(busy)return;busy=true;send.disabled=true;signIn.disabled=signUp.disabled=true;try{
 const session=await customerDataClient.auth.getSession();if(session.error)throw session.error;if(session.data.session?.user?.email_confirmed_at){await savePassword();if(!contacts.hidden){pendingName=document.getElementById('userName').value.trim();pendingPhone=document.getElementById('userPhone').value.trim();if(!pendingName||!pendingPhone)throw Error('Enter your name and delivery contact phone.');}await finish(true);return;}
 if(mode==='signin'){if(!email.checkValidity()||!email.value.trim())throw Error('Enter a valid email address.');validatePassword();const {error}=await customerDataClient.auth.signInWithPassword({email:email.value.trim(),password:password.value});if(error)throw Error(/invalid login credentials/i.test(error.message)?'Email or password is incorrect. If you previously used an email code, choose “Forgot password or need to set one?”.':error.message);password.value='';resetContact();await finish(true);return;}
 if(!pendingEmail){if(!email.checkValidity()||!email.value.trim())throw Error('Enter a valid email address.');validatePassword();resetContact();pendingEmail=email.value.trim();passwordSaved=false;const {error}=await customerDataClient.auth.signInWithOtp({email:pendingEmail,options:{shouldCreateUser:mode==='signup'}});if(error){pendingEmail='';throw error;}email.readOnly=true;code.hidden=false;codeLabel.hidden=false;change.hidden=false;recover.hidden=true;send.textContent='Verify & continue';status.textContent='Check your email and enter the verification code.';code.focus();}
 else{const token=code.value.trim();if(!/^\d{6,10}$/.test(token))throw Error('Enter the code from your email.');const {error}=await customerDataClient.auth.verifyOtp({email:pendingEmail,token,type:'email'});if(error)throw error;await savePassword();await finish(true);}
 }catch(e){status.textContent=e.message;}finally{busy=false;send.disabled=false;signIn.disabled=signUp.disabled=!!pendingEmail;}};
 function clearPassword(){passwordSaved=false;password.value=confirm.value='';password.hidden=passwordLabel.hidden=false;}
 const change=make('button','Start over');change.type='button';change.id='customerAuthChange';change.hidden=true;change.onclick=async()=>{if(busy)return;await customerDataClient.auth.signOut();pendingEmail='';clearPassword();resetContact();change.hidden=true;email.readOnly=false;code.hidden=true;codeLabel.hidden=true;code.value='';status.textContent='';mode='signin';renderMode();};send.after(change);
 const logout=window.handleLogout;window.handleLogout=async function(...args){await customerDataClient.auth.signOut();document.documentElement?.classList.add('swift-awaiting-auth');pendingEmail='';clearPassword();resetContact();change.hidden=true;email.readOnly=false;code.hidden=true;codeLabel.hidden=true;mode='signin';renderMode();return logout.apply(this,args);};
 window.saveProfile=async()=>{try{const result=await customerDataClient.rpc('swift_customer_profile',{p_name:document.getElementById('profileName').value.trim()});if(result.error)throw result.error;localStorage.setItem('userName',result.data.name);localStorage.setItem('userPhone',result.data.phone);document.getElementById('profileDisplayName').textContent=result.data.name;document.getElementById('profilePhone').value=result.data.phone;}catch(e){alert(e.message);}};
 const phoneField=document.getElementById('profilePhone');if(phoneField){phoneField.readOnly=true;phoneField.title='Contact support to change the account phone safely.';}
 const restorePanel=document.getElementById('customerSessionRestore');
 async function restoreSession(){
  try{const r=await customerDataClient.auth.getSession();if(r.error)throw r.error;
   if(!r.data.session?.user?.email_confirmed_at){restorePanel.hidden=true;authScreen();return;}
   document.getElementById('authScreen').style.display='none';restorePanel.hidden=false;
   document.getElementById('customerSessionRestoreStatus').textContent='Welcome back';
   document.getElementById('customerSessionRetry').hidden=true;document.getElementById('customerSessionLogout').hidden=true;
   if(await finish(true))restorePanel.hidden=true;else{restorePanel.hidden=true;authScreen();}
  }catch(e){document.getElementById('authScreen').style.display='none';restorePanel.hidden=false;document.getElementById('customerSessionRestoreStatus').textContent='Could not reconnect. Your saved session has not been signed out.';document.getElementById('customerSessionRetry').hidden=false;document.getElementById('customerSessionLogout').hidden=false;}
  finally{document.documentElement?.classList.remove('swift-restoring-auth');}
 }
 document.getElementById('customerSessionRetry').onclick=restoreSession;
 document.getElementById('customerSessionLogout').onclick=async()=>{await window.handleLogout();restorePanel.hidden=true;authScreen();};
 restoreSession();
 });
})();
