(() => {
 'use strict';
 const client=()=>window.SwiftAdmin?.verified?window.SwiftAdmin.client:null;
 const make=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
 async function rpc(name,args){const c=client();if(!c)throw Error('Administrator sign-in required.');const {data,error}=await c.rpc(name,args).abortSignal(AbortSignal.timeout(15000));if(error)throw error;return data;}
 let dialog,form,status,current=null,requestId=null,busy=false;
 function open(user){current=user;requestId=crypto.randomUUID();form.reset();dialog.querySelector('[data-customer]').textContent=user.name||'Customer';dialog.querySelector('[data-current]').textContent='Current balance: BZ$'+Number(user.balance||0).toFixed(2);form.elements.balance.value=Number(user.balance||0).toFixed(2);status.textContent='Confirm the recharge payment before increasing a balance.';dialog.showModal();form.elements.balance.focus();}
 document.addEventListener('DOMContentLoaded',()=>{
  dialog=make('dialog');dialog.id='swiftPayAdminDialog';dialog.className='swiftpay-qr-dialog swiftpay-admin-dialog';dialog.setAttribute('aria-label','Adjust customer SwiftPay balance');dialog.innerHTML='<button type="button" data-close aria-label="Close balance adjustment">✕</button><p class="swiftpay-eyebrow">ADMINISTRATOR CONTROL</p><h2>Adjust SwiftPay balance</h2><strong data-customer></strong><p data-current></p><form><label>New balance (BZD)<input name="balance" type="number" min="0" max="100000" step="0.01" inputmode="decimal" required></label><label>Reason<textarea name="reason" rows="3" minlength="3" maxlength="500" placeholder="Payment confirmed · recharge reference…" required></textarea></label><p data-status role="status" aria-live="polite"></p><button class="swiftpay-primary" type="submit">Save balance adjustment</button></form>';document.body.append(dialog);form=dialog.querySelector('form');status=dialog.querySelector('[data-status]');dialog.querySelector('[data-close]').onclick=()=>{if(!busy)dialog.close();};dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});
  form.onsubmit=async e=>{e.preventDefault();if(busy||!current)return;const amount=Number(form.elements.balance.value);const cents=Math.round(amount*100);if(!Number.isFinite(amount)||Math.abs(cents/100-amount)>0.000001||cents<0)return status.textContent='Enter a valid balance with at most two decimal places.';busy=true;form.querySelector('button').disabled=true;status.textContent='Saving audited adjustment…';try{const data=await rpc('swiftpay_admin_adjust',{p_profile_id:current.id,p_balance_cents:cents,p_reason:form.elements.reason.value.trim(),p_request_id:requestId,p_expected_balance_cents:Math.round(Number(current.balance||0)*100)});status.textContent='Balance saved: BZ$'+(data.balanceCents/100).toFixed(2)+'. Adjustment recorded.';await window.fetchAdminUsers();form.querySelector('button').textContent='Adjustment saved';form.elements.balance.disabled=true;form.elements.reason.disabled=true;}catch(error){status.textContent=error.message;form.querySelector('button').disabled=false;}finally{busy=false;}};
  const original=window.fetchAdminUsers;
  window.fetchAdminUsers=async function(){const host=document.getElementById('adminUsersList');if(!host)return;host.textContent='Loading customers…';try{const c=client();if(!c)throw Error('Administrator sign-in required.');const {data,error}=await c.from('swiftshop_users').select('id,name,email,phone,contact_phone,points,balance,auth_user_id').order('timestamp',{ascending:false}).abortSignal(AbortSignal.timeout(15000));if(error)throw error;host.replaceChildren();for(const u of data||[]){const row=make('article');row.className='swiftpay-admin-user';const copy=make('div');copy.append(make('strong',u.name||'Customer'),make('small',(u.contact_phone||u.phone||'')+' · '+(u.email||'No email')));const controls=make('div');controls.append(make('small',String(u.points||0)+' points'));const adjust=make('button','SwiftPay · BZ$'+Number(u.balance||0).toFixed(2)+' ✎');adjust.type='button';adjust.disabled=!u.auth_user_id;adjust.setAttribute('aria-label','Adjust SwiftPay balance for '+(u.name||'customer'));adjust.onclick=()=>{form.elements.balance.disabled=false;form.elements.reason.disabled=false;form.querySelector('button').disabled=false;form.querySelector('button').textContent='Save balance adjustment';open(u);};controls.append(adjust);row.append(copy,controls);host.append(row);}if(!data?.length)host.textContent='No customers yet.';}catch(error){host.textContent=error.message;}};
  window.SwiftPayAdmin={quotePickup:async(id,cents)=>rpc('swiftpay_quote_pickup',{p_id:id,p_amount_cents:cents})};
 });
})();
