(() => {
 'use strict';
 const money=cents=>'BZ$'+(Number(cents||0)/100).toFixed(2);
 const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const button=(text,fn,cls)=>{const n=node('button',text,cls);n.type='button';n.onclick=fn;return n;};
 const customer=()=>typeof customerDataClient!=='undefined'?customerDataClient:null;
 async function rpc(client,name,args={}){if(!client)throw Error('Sign in to continue.');const {data,error}=await client.rpc(name,args).abortSignal(AbortSignal.timeout(15000));if(error)throw error;return data;}
 let page,notice,cardName,cardAmount,heldLabel,history,requests,qrDialog,qrStatus,qrCanvas,qrSummary,currentQR=null,poll=null,version=0,busy=false;
 let wallet=null,account='';
 const scope=()=>localStorage.getItem('userPhone')||'';
 const active=()=>page&&!page.hidden;
 async function refresh(){const identity=scope(),stamp=++version;try{const data=await rpc(customer(),'swiftpay_wallet');if(stamp!==version||identity!==scope())return;wallet=data;account=identity;draw();window.dispatchEvent(new Event('swiftpay-wallet-updated'));notice.textContent='';const value=document.getElementById('userBalance');if(value)value.textContent=(data.availableCents/100).toFixed(2);if(currentQR){const p=data.payments.find(x=>x.kind===currentQR.kind&&x.reference_id===currentQR.id);if(p?.state==='captured'){clearInterval(poll);qrCanvas.hidden=true;qrDialog.classList.add('swiftpay-paid');qrStatus.textContent='Payment successful';qrSummary.textContent=money(p.amount_cents+p.fee_cents)+' paid · '+money(data.availableCents)+' available';qrDialog.querySelector('[data-qr-mark]').hidden=false;qrDialog.querySelector('[data-refresh-code]').hidden=true;window.dispatchEvent(new Event('swiftpay-paid'));}}}catch(e){if(stamp===version){notice.textContent=e.message;notice.setAttribute('role','alert');}}}
 function draw(){if(!wallet)return;cardName.textContent=wallet.name||'SwiftShop customer';cardAmount.textContent=money(wallet.availableCents);heldLabel.textContent=wallet.reservedCents?money(wallet.reservedCents)+' reserved for active requests':'Ready for your next delivery, pickup or ride';history.replaceChildren();if(!wallet.transactions.length)history.append(node('p','Your payments and top-ups will appear here.','swiftpay-empty'));for(const t of wallet.transactions){const row=node('article',undefined,'swiftpay-transaction');const copy=node('div');copy.append(node('strong',t.kind==='payment'?'SwiftPay '+(t.reference_kind==='ride'?'ride':'order'):'Balance adjustment'),node('small',new Date(t.created_at).toLocaleString()));const amount=t.kind==='payment'?t.amount_cents-t.fee_cents:t.amount_cents;row.append(copy,node('strong',(amount>0?'+':'−')+money(Math.abs(amount)),amount>0?'swiftpay-credit':''));history.append(row);}requests.replaceChildren();const pending=wallet.payments.filter(p=>['quoted','reserved'].includes(p.state));if(!pending.length)requests.append(node('p','No payments waiting.','swiftpay-empty'));for(const p of pending){const row=node('article',undefined,'swiftpay-payment-row');const copy=node('div');copy.append(node('strong',(p.kind==='ride'?'Ride':'Order')+' #'+p.reference_id.slice(0,8).toUpperCase()),node('small',money(p.amount_cents)+' + BZ$0.15 fee'));const action=button(p.state==='quoted'?'Accept fee · '+money(p.amount_cents+15):'Pay',async()=>{if(busy)return;busy=true;action.disabled=true;try{if(p.state==='quoted'){await rpc(customer(),'swiftpay_accept_pickup_fee',{p_id:p.reference_id,p_expected_total_cents:p.amount_cents+15});await refresh();}else await pay(p.kind,p.reference_id);}catch(e){notice.textContent=e.message;}finally{busy=false;action.disabled=false;}},'swiftpay-primary');const actions=node('div');actions.append(action);if(p.kind==='delivery'){actions.append(button('Cancel before dispatch',async()=>{try{await rpc(customer(),'swiftpay_cancel_pending',{p_id:p.reference_id});await refresh();}catch(e){notice.textContent=e.message;}},'swiftpay-cancel'));}row.append(copy,actions);requests.append(row);}}
 function close(){page.hidden=true;page.inert=true;document.body.classList.remove('swiftpay-open');clearInterval(poll);qrDialog?.close();window.SwiftNavigation?.refresh();document.querySelector('.sd-header-balance')?.focus();}
 async function open(){page.hidden=false;page.inert=false;document.body.classList.add('swiftpay-open');notice.textContent='Loading your secure wallet…';window.SwiftNavigation?.refresh();page.querySelector('h1').focus();await refresh();}
 async function pay(kind,id){currentQR={kind,id};qrDialog.classList.remove('swiftpay-paid');qrDialog.querySelector('[data-qr-mark]').hidden=true;qrDialog.querySelector('[data-refresh-code]').hidden=false;qrCanvas.hidden=true;qrStatus.textContent='Preparing your secure payment code…';qrSummary.textContent='';if(!qrDialog.open)qrDialog.showModal();window.SwiftNavigation?.refresh();try{const data=await rpc(customer(),'swiftpay_payment_code',{p_kind:kind,p_id:id});if(!qrDialog.open||currentQR?.id!==id)return;if(data.paid){await refresh();return;}qrSummary.textContent=money(data.amountCents)+' + BZ$0.15 fee · Total '+money(data.totalCents);await window.SwiftQRCode.toCanvas(qrCanvas,data.payload,{width:232,margin:3,errorCorrectionLevel:'M',color:{dark:'#18221cff',light:'#ffffffff'}});qrCanvas.hidden=false;qrStatus.textContent='Show this code only to your assigned runner or driver. Payment and completion happen together after they confirm the scan.';clearInterval(poll);poll=setInterval(()=>{if(!document.hidden)refresh();},4000);}catch(e){qrStatus.textContent=e.message;}}
 window.SwiftPay={open,close,pay,refresh,payment(kind,id){return account===scope()?wallet?.payments?.find(p=>p.kind===kind&&p.reference_id===id):null;},get availableCents(){return wallet&&account===scope()?wallet.availableCents:null;}};
 document.addEventListener('DOMContentLoaded',()=>{
  page=node('section',undefined,'swiftpay-page');page.id='swiftPayPage';page.hidden=true;page.inert=true;page.setAttribute('aria-label','SwiftPay prepaid wallet');
  page.innerHTML='<div class="swiftpay-shell"><header class="swiftpay-header"><button type="button" data-back aria-label="Back to home">←</button><div><p>YOUR PREPAID WALLET</p><h1 tabindex="-1">SwiftPay</h1></div><span>PREPAID</span></header><section class="swiftpay-card" aria-label="SwiftPay virtual prepaid card"><div class="swiftpay-card-top"><strong>Swift<span>Pay</span></strong><span>BZD</span></div><p>AVAILABLE TO SPEND</p><strong data-amount class="swiftpay-card-amount">—</strong><small data-held>Loading your wallet</small><div class="swiftpay-card-bottom"><div><small>CARDHOLDER</small><strong data-name></strong></div><span aria-hidden="true">◉</span></div></section><p data-notice role="status" aria-live="polite"></p><section class="swiftpay-recharge"><div><h2>A little top-up. More possibilities.</h2><p>Contact SwiftShop to arrange your recharge. Your balance updates after we confirm payment.</p></div><div><a href="https://wa.me/5016080205?text=Hi%20SwiftShop%2C%20I%27d%20like%20to%20recharge%20my%20SwiftPay%20wallet." target="_blank" rel="noopener">WhatsApp · 6080205 ↗</a><a href="mailto:dancu1213t@gmail.com?subject=SwiftPay%20recharge">Email SwiftShop ↗</a></div></section><section class="swiftpay-section"><div class="swiftpay-section-heading"><h2>Ready to pay</h2><span>BZ$0.15 per payment</span></div><div data-requests></div></section><section class="swiftpay-section"><div class="swiftpay-section-heading"><h2>Recent activity</h2><button type="button" data-wallet-refresh>Refresh</button></div><div data-history></div></section><p class="swiftpay-footnote">Use SwiftPay for SwiftShop deliveries, already-paid store pickups and rides. Your virtual prepaid card is for SwiftShop payments.</p></div>';
  document.body.append(page);notice=page.querySelector('[data-notice]');cardName=page.querySelector('[data-name]');cardAmount=page.querySelector('[data-amount]');heldLabel=page.querySelector('[data-held]');history=page.querySelector('[data-history]');requests=page.querySelector('[data-requests]');page.querySelector('[data-back]').onclick=close;page.querySelector('[data-wallet-refresh]').onclick=refresh;
  qrDialog=node('dialog',undefined,'swiftpay-qr-dialog');qrDialog.id='swiftPayPaymentDialog';qrDialog.setAttribute('aria-label','Authorize SwiftPay payment');qrDialog.innerHTML='<button type="button" data-qr-close aria-label="Close payment code">✕</button><p class="swiftpay-eyebrow">SWIFTPAY</p><div data-qr-mark class="swiftpay-success-mark" hidden>✓</div><h2>Pay. Scan. All done.</h2><p data-qr-summary></p><canvas aria-label="Private one-time SwiftPay payment QR code"></canvas><p data-qr-status role="status" aria-live="polite"></p><button type="button" data-refresh-code>Refresh payment code</button>';document.body.append(qrDialog);qrCanvas=qrDialog.querySelector('canvas');qrStatus=qrDialog.querySelector('[data-qr-status]');qrSummary=qrDialog.querySelector('[data-qr-summary]');qrDialog.querySelector('[data-qr-close]').onclick=()=>qrDialog.close();qrDialog.querySelector('[data-refresh-code]').onclick=()=>currentQR&&pay(currentQR.kind,currentQR.id);qrDialog.addEventListener('close',()=>{clearInterval(poll);currentQR=null;});
  const value=document.getElementById('userBalance'),balance=value?.closest('.sd-header-balance')||value?.parentElement;if(balance){balance.setAttribute('role','button');balance.tabIndex=0;balance.setAttribute('aria-label','Open SwiftPay prepaid wallet');const label=balance.querySelector('.sd-balance-label');if(label)label.textContent='SWIFTPAY';balance.append(node('small','Prepaid','swiftpay-balance-tag'));balance.onclick=open;balance.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}};}
  const payment=document.getElementById('paymentMethod');payment?.addEventListener('change',()=>{if(payment.value==='SwiftPay')refresh();if(typeof refreshCartTotals==='function')refreshCartTotals();});
  const rideFare=document.getElementById('crFareBox');if(rideFare){const label=node('label','Payment method','swiftpay-method-label'),select=node('select');select.id='crPaymentMethod';select.append(new Option('Cash','Cash'),new Option('SwiftPay · Prepaid','SwiftPay'));label.append(select);const fee=node('p',undefined,'swiftpay-method-note');fee.id='swiftpayRideFee';rideFare.append(label,fee);const update=()=>{const fare=Number((document.getElementById('crFareTotal')?.textContent||'').replace(/[^0-9.]/g,''));fee.textContent=select.value==='SwiftPay'?'BZ$0.15 SwiftPay fee · Total '+money(Math.round(fare*100)+15):'Pay your driver at the end of the trip.';};select.onchange=()=>{update();if(select.value==='SwiftPay')refresh();};const total=document.getElementById('crFareTotal');if(total)new MutationObserver(update).observe(total,{childList:true,subtree:true,characterData:true});update();}
  const pickup=document.getElementById('pickupOrderBox');if(pickup){const label=node('label','Payment method','swiftpay-method-label'),select=node('select');select.id='pickupPaymentMethod';select.append(new Option('Arrange payment with SwiftShop','Cash'),new Option('SwiftPay · Service fee only','SwiftPay'));label.append(select);const note=node('p','For SwiftPay pickups, store items must already be paid. SwiftShop sends your service fee for you to accept before dispatch. BZ$0.15 applies when payment completes.','swiftpay-method-note');const paid=node('label',undefined,'swiftpay-pickup-paid');const check=node('input');check.type='checkbox';check.id='pickupStorePaid';paid.append(check,document.createTextNode('I have already paid the store for these items.'));paid.hidden=true;select.onchange=()=>{paid.hidden=select.value!=='SwiftPay';};const submit=pickup.querySelector('[onclick="sendPickupWhatsApp()"]');submit?.before(label,note,paid);}
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&active()&&!qrDialog.open)close();});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&(active()||qrDialog.open))refresh();});
  setInterval(()=>{if(scope()!==account){wallet=null;account=scope();version++;if(!account)close();else refresh();}},1500);
  const logout=window.handleLogout;if(logout)window.handleLogout=async function(...args){close();wallet=null;return logout.apply(this,args);};
 });
})();
